In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

**Criando arrays usando listas**

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

**Criando array por atribuição**

In [4]:
np.random.seed(25)
b = randn(6)
b

array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

In [5]:
c = np.arange(1, 35)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

**Operações aritm´rticas