In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

## Multiplicando matrizes e arrays

In [4]:
a = np.arange(3)
a

array([0, 1, 2])

In [6]:
aa = np.array([[2., 4., 6.], [1., 3., 5.], [10., 20., 30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [7]:
a * aa

array([[ 0.,  4., 12.],
       [ 0.,  3., 10.],
       [ 0., 20., 60.]])

## Multiplicando matrizes

In [8]:
bb = np.arange(9).reshape((3,3))
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
aa * bb ##errado

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [11]:
np.dot(aa, bb) ##certo

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [12]:
b = a * 3
b

array([0, 3, 6])

In [13]:
np.dot(a, b) ##escalar

15